platform :ios, '11.0'
use_frameworks!

target 'Aladin_Example' do
#  pod 'Aladin', :git => 'https://github.com/ALADINIO/ios-sdk.git'
  pod 'Aladin', :path => '../'
end

target 'Aladin_Tests' do
  inherit! :search_paths
  pod 'Aladin', :path => '../'
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
end
